use std::{
    collections::{BTreeMap, HashMap},
    io::{BufRead, BufReader, Read, Write},
    path::{Path, PathBuf},
    process::{Child, ChildStdin, Command, Stdio},
};

use config_file2::LoadConfigFile;
use log::{debug, info, warn};
use parking_lot::Mutex;
use zeroize::Zeroizing;

use crate::{
    config::{CONFIG_FILE_NAME, Config},
    error::{Error, Result},
    filter::is_ciphertext,
    gitattributes,
    utils::{
        Progress, atomic_write, is_file_encrypted, parallel, prompt_password, resolve_target_files,
        style::Colorize,
    },
};

pub const GIT_CONFIG_PREFIX: &str =
    const_str::replace!(concat!(env!("CARGO_CRATE_NAME"), "."), "_", "-");

/// Marker line embedded in every hook generated by git-se (the line right
/// below the shebang).
///
/// A unit test locks the template's second line to this constant so the
/// managed-hook detection cannot drift from the template.
const PRE_COMMIT_HOOK_MARKER: &[u8] = b"# Auto-generated by git-se install";

/// Build the pre-commit hook content that runs `git-se check --staged`
/// before every commit, so only files part of the current commit are
/// checked.
///
/// The hook invokes the running executable by absolute path (shell-quoted,
/// forward-slashed): a bare `git-se` would depend on PATH, and GUI clients
/// or CI images that never install it there would have every commit blocked
/// by a missing binary. This mirrors the absolute-path approach already
/// used for the filter driver config.
fn pre_commit_hook(exe_quoted: &str) -> Vec<u8> {
    format!(
        "#!/bin/sh\n{}\n{exe_quoted} check --staged\nif [ $? -ne 0 ]; then\n    echo \"Please run \
         'git-se e' to encrypt them before committing.\"\n    exit 1\nfi\n",
        String::from_utf8_lossy(PRE_COMMIT_HOOK_MARKER),
    )
    .into_bytes()
}

/// Whether the pre-commit hook at `hook_path` is managed by git-se
/// (recognized by the marker line below the shebang).
fn is_managed_hook(hook_path: &Path) -> Result<bool> {
    if !hook_path.exists() {
        return Ok(false);
    }
    let existing = std::fs::read(hook_path)?;
    Ok(existing
        .split(|&b| b == b'\n')
        .take(2) // shebang + marker line
        .any(|line| line.trim_ascii() == PRE_COMMIT_HOOK_MARKER))
}

/// Shell-quote an executable path for embedding in sh snippets and config
/// command lines: forward slashes work in both POSIX and MSYS sh, and single
/// quotes make everything else shell-safe.
fn quote_exe_for_sh(exe: &Path) -> String {
    let exe = exe.to_string_lossy().replace('\\', "/");
    format!("'{}'", exe.replace('\'', "'\\''"))
}

/// A persistent `git cat-file --batch` session.
///
/// Spawning one git process per blob costs 20-50ms on Windows; at a thousand
/// staged files the pre-commit check spent 30-50s just spawning git. One
/// session serves any number of lookups over a single pipe pair. Requests
/// are answered strictly in lockstep (write one request line, then read the
/// full response) so arbitrarily large blobs cannot deadlock on a full
/// pipe.
struct CatFileBatch {
    child: Child,
    stdin: ChildStdin,
    stdout: BufReader<std::process::ChildStdout>,
}

impl CatFileBatch {
    fn spawn(cwd: &Path) -> Result<Self> {
        let mut child = Command::new("git")
            .current_dir(cwd)
            .args(["cat-file", "--batch"])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            // Per-object errors are conveyed by the batch protocol itself
            // ("<spec> missing"); git's stderr would only add noise.
            .stderr(Stdio::null())
            .spawn()?;
        let stdin = child
            .stdin
            .take()
            .ok_or_else(|| Error::Other("git cat-file stdin unavailable".to_string()))?;
        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| Error::Other("git cat-file stdout unavailable".to_string()))?;
        Ok(Self {
            child,
            stdin,
            stdout: BufReader::new(stdout),
        })
    }

    /// Read one blob by its object id; `None` when the object is missing.
    ///
    /// Response framing: `<oid> <type> <size> LF <size bytes> LF`, or
    /// `<spec> missing LF`.
    fn blob(&mut self, oid: &str) -> Result<Option<Vec<u8>>> {
        self.stdin.write_all(oid.as_bytes())?;
        self.stdin.write_all(b"\n")?;
        self.stdin.flush()?;
        let mut header = String::new();
        self.stdout.read_line(&mut header)?;
        let header = header.trim_end();
        // Response header: `<oid> <type> <size>` or `<spec> missing`.
        let Some(size) = header
            .rsplit_once(' ')
            .and_then(|(_, size)| size.parse::<usize>().ok())
        else {
            if header.ends_with(" missing") {
                return Ok(None);
            }
            return Err(Error::Other(format!(
                "unexpected git cat-file response: {header}"
            )));
        };
        // Payload of exactly `size` bytes, then one LF terminator.
        let mut buf = vec![0u8; size + 1];
        self.stdout.read_exact(&mut buf)?;
        buf.truncate(size);
        Ok(Some(buf))
    }
}

impl Drop for CatFileBatch {
    fn drop(&mut self) {
        // The session lives exactly as long as the caller's questions;
        // kill+reap deterministically cleans up even mid-stream.
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

/// Split raw NUL-terminated git output into records (dropping the empty
/// trailing record). Every multi-path git parse goes through here so the
/// `-z` handling lives in exactly one place.
fn nul_records(bytes: &[u8]) -> impl Iterator<Item = &[u8]> {
    bytes.split(|&b| b == 0).filter(|r| !r.is_empty())
}

/// Split a byte record at its first `sep` byte (`slice::split_once` is not
/// stable for byte slices yet).
fn split_byte_record(record: &[u8], sep: u8) -> Option<(&[u8], &[u8])> {
    record
        .iter()
        .position(|&b| b == sep)
        .map(|i| (&record[..i], &record[i + 1..]))
}

/// Whether a repo-relative path (forward slashes) is covered by the crypt
/// list: an exact file entry, or an entry naming an ancestor directory.
///
/// Deliberately free of the walker's ignore semantics: this predicate feeds
/// staged/index queries, and a tracked, staged file must never be hidden by
/// .gitignore rules (the pre-commit check would silently skip it). Crypt
/// entries are plain paths, never globs, so the prefix test is exact.
fn crypt_covers(crypt_list: &[String], rel: &str) -> bool {
    crypt_list
        .iter()
        .any(|e| rel == e || rel.starts_with(&format!("{e}/")))
}

#[derive(Debug, Clone)]
pub struct Repo {
    /// The absolute worktree root this repo was opened from.
    ///
    /// Public for v3 source compatibility, but treat it as read-only: it
    /// must stay the absolute worktree root that [`Repo::open`] /
    /// [`Repo::discover`] validated, and mutating it bypasses that
    /// validation. There is intentionally no `Default` — a defaulted
    /// instance is an invalid one.
    pub path: PathBuf,
    pub conf: Config,
}

impl Repo {
    /// Open a repo. The `path` argument must be an absolute path.
    pub fn open(path: impl AsRef<Path>) -> Result<Self> {
        debug_assert!(path.as_ref().is_absolute(), "given path must be absolute");
        let mut repo_path = path.as_ref().to_path_buf();
        if !repo_path.exists() {
            return Err(Error::RepoNotFound(repo_path));
        }
        if !repo_path.is_dir() {
            return Err(Error::NotADirectory(repo_path));
        }
        if repo_path
            .file_name()
            .ok_or_else(|| Error::Other("Filename not found".to_string()))?
            == ".git"
        {
            repo_path.pop();
        }
        // A usable work tree must contain a `.git` entry: either a directory
        // (normal clone) or a `gitdir: <path>` pointer file (linked worktree /
        // submodule). Rejecting other directories up front avoids obscure git
        // errors from `get_key()`. The salt cache resolves such pointer files
        // to the real gitdir on its own (see `salt_cache::resolve_git_dir`),
        // so cache writes keep working from linked worktrees too.
        // No dedicated Error variant for v3 compatibility (the enum is not
        // `#[non_exhaustive]`); the message rides in `Error::Other`.
        let dot_git = repo_path.join(".git");
        if !dot_git.is_dir() && !dot_git.is_file() {
            return Err(Error::Other(format!(
                "not a git repository: {}",
                repo_path.display()
            )));
        }
        info!("Open repo: {}", repo_path.display());
        let config_file_path = repo_path.join(CONFIG_FILE_NAME);
        if !config_file_path.exists() {
            warn!(
                "Config file not found: `{}`, using default config instead...",
                config_file_path.display()
            );
        }
        let conf = Config::load_or_default(&config_file_path)
            .map_err(|e| Error::Config(e.to_string()))?
            .with_repo_path(&repo_path);
        Ok(Self {
            path: repo_path,
            conf,
        })
    }

    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn to_absolute_path(&self, path: impl AsRef<Path>) -> PathBuf {
        self.path.join(path.as_ref())
    }

    /// Read the master key from git config.
    ///
    /// Returns an error if the key has not been configured. The returned
    /// string is zeroized on drop.
    pub fn get_key(&self) -> Result<Zeroizing<String>> {
        self.get_config("key").map(Zeroizing::new).map_err(|e| {
            Error::Other(format!(
                "Key not found, please run `git-se p` (or `git-se set key <VALUE>`) first: {e}"
            ))
        })
    }

    /// Set the key interactively by prompting on stdin.
    pub fn set_key_interactive(&self) -> Result<()> {
        let key = prompt_password("Please input your key: ")?;
        self.set_config("key", key.as_str())?;
        info!("Master key updated.");
        Ok(())
    }

    /// Check if all files in the crypt list (or given paths) are encrypted.
    ///
    /// When `staged` is true, only files staged for the current commit are
    /// checked, and their *staged blobs* are inspected — the blob is what
    /// the commit would actually write, so a worktree file that was
    /// encrypted, edited or deleted after staging cannot mask a staged
    /// plaintext (see [`Repo::check_staged`]). This is the mode the
    /// pre-commit hook uses.
    ///
    /// Returns `Ok(())` if all files are encrypted, or an error summarizing
    /// which files are not encrypted. The process exits with a non-zero code
    /// when files are not encrypted, suitable for CI usage.
    pub fn check(&self, paths: &[PathBuf], staged: bool) -> Result<()> {
        // In filter mode the working tree stays plaintext by design, so
        // checking worktree files would always fail and report nothing
        // useful. The staged check stays meaningful: it inspects the staged
        // blobs that will actually be committed.
        let filter_mode = self.filter_installed();
        if filter_mode && !staged {
            println!(
                "Filter integration is active: working-tree files stay plaintext and are \
                 encrypted automatically by git; only `check --staged` is meaningful (it inspects \
                 the staged blobs)."
            );
            return Ok(());
        }

        if staged {
            return self.check_staged();
        }

        let target_files = resolve_target_files(paths, &self.conf.crypt_list, self.path());
        if target_files.is_empty() {
            return Err(Error::NoFile("check"));
        }
        self.check_worktree(&target_files)
    }

    /// `check --staged`: inspect the staged blobs of crypt-list files.
    ///
    /// Enumeration uses `git diff --cached --name-only -z` (raw NUL-separated
    /// paths: `-z` disables C-quoting, so paths with `"`, backslashes,
    /// spaces or non-ASCII survive byte-for-byte) and membership is a plain
    /// prefix test against the crypt list. Blob contents come from
    /// `git ls-files -s` oids through a single [`CatFileBatch`] session —
    /// never from a per-file `exists()` worktree check, which used to drop
    /// staged files whose worktree copy had been deleted (F7a) and masked
    /// staged plaintext under an already-encrypted worktree file.
    fn check_staged(&self) -> Result<()> {
        let targets = self.staged_crypt_blobs()?;
        if targets.is_empty() {
            println!("No staged files need encryption check.");
            return Ok(());
        }

        println!(
            "\n{} {} {}",
            "Checking encryption status".bold(),
            format!("({} files)", targets.len()).cyan(),
            ":".dimmed()
        );

        let pb = Progress::new(targets.len(), "Check");
        let mut not_encrypted: Vec<String> = Vec::new();
        let mut first_error: Option<Error> = None;
        let mut batch = CatFileBatch::spawn(&self.path)?;
        for (rel, oid) in &targets {
            match batch.blob(oid) {
                Ok(Some(blob)) => {
                    if !is_ciphertext(&blob) {
                        not_encrypted.push(rel.clone());
                    }
                },
                Ok(None) => warn!("staged blob {oid} of {rel} is missing from the object store"),
                Err(e) => {
                    warn!("Failed to read staged blob of {rel}: {e}");
                    first_error.get_or_insert(e);
                },
            }
            pb.inc(1);
        }
        pb.finish_and_clear();

        // Every error was logged above; surface the first one as the return value.
        if let Some(first) = first_error {
            return Err(first);
        }
        report_check(&not_encrypted, targets.len())
    }

    /// Check worktree files (manual/hook mode; filter mode never gets here).
    fn check_worktree(&self, target_files: &[PathBuf]) -> Result<()> {
        println!(
            "\n{} {} {}",
            "Checking encryption status".bold(),
            format!("({} files)", target_files.len()).cyan(),
            ":".dimmed()
        );

        let pb = Progress::new(target_files.len(), "Check");
        let not_encrypted: Mutex<Vec<String>> = Mutex::new(Vec::new());
        let errors: Mutex<Vec<Error>> = Mutex::new(Vec::new());

        parallel::for_each(target_files, |f| {
            match is_file_encrypted(f) {
                Ok(false) => {
                    let mut list = not_encrypted.lock();
                    let relative = pathdiff::diff_paths(f, &self.path).unwrap_or_else(|| f.clone());
                    list.push(relative.display().to_string());
                },
                Ok(true) => {},
                Err(e) => {
                    warn!("Failed to check {}: {e}", f.display());
                    errors.lock().push(e);
                },
            }
            pb.inc(1);
        });

        // Clear the progress bar on every exit path, error or not.
        pb.finish_and_clear();

        // Every error was logged above; surface the first one as the return value.
        if let Some(first) = errors.into_inner().into_iter().next() {
            return Err(first);
        }
        report_check(&not_encrypted.into_inner(), target_files.len())
    }

    /// Install a pre-commit hook that runs `git-se check` before each commit.
    ///
    /// Creates the pre-commit hook wherever git looks for hooks in this repo
    /// (a local `core.hooksPath` wins; otherwise the shared hooks dir of the
    /// common gitdir — linked worktrees read the main repository's hooks).
    /// Hooks previously installed by git-se (recognized by the marker line)
    /// are overwritten, so installing again also upgrades an outdated hook.
    /// Fails if a hook exists that is not managed by git-se.
    pub fn install_hook(&self) -> Result<()> {
        let (hooks_dir, foreign_hooks_path) = self.hooks_dir()?;
        std::fs::create_dir_all(&hooks_dir)?;

        let hook_path = hooks_dir.join("pre-commit");

        // An existing hook may only be overwritten when it is managed by
        // git-se (marker line below the shebang). Anything else is user
        // content and must be removed manually.
        if hook_path.exists() && !is_managed_hook(&hook_path)? {
            return Err(Error::HookExists(hook_path));
        }

        // Absolute exe path survives PATH changes; forward slashes work in
        // both POSIX sh and MSYS sh; single quotes make it shell-safe.
        let exe = std::env::current_exe()
            .map_err(|e| Error::Other(format!("failed to locate the running executable: {e}")))?;
        std::fs::write(&hook_path, pre_commit_hook(&quote_exe_for_sh(&exe)))?;

        // Set executable permission on unix. Windows users need Git for Windows
        // (msys-based) which executes the sh hook regardless of the executable
        // bit; a normal `write` is sufficient there.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&hook_path)?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&hook_path, perms)?;
        }

        println!(
            "{} pre-commit hook at {}",
            "Installed".green().bold(),
            hook_path.display()
        );
        if foreign_hooks_path {
            println!(
                "{}",
                "Note: core.hooksPath is set outside this repository (global/system scope); git \
                 may run hooks from there instead. Set a repo-local `git config core.hooksPath` \
                 if the hook does not trigger."
                    .yellow()
            );
        }
        Ok(())
    }

    /// Where git looks for hooks in this repository, plus whether a
    /// non-local `core.hooksPath` is in effect (the caller warns: the hook
    /// may be bypassed).
    ///
    /// 1. A repo-local `core.hooksPath` wins. Git resolves a relative value against the directory
    ///    it runs hooks from — the worktree root here. Only the LOCAL scope is honored: `git
    ///    rev-parse --git-path hooks` follows global `core.hooksPath` too, and writing a
    ///    repo-scoped hook into a hooks dir shared by every repository of that user would be far
    ///    worse than a warning.
    /// 2. Otherwise the hooks dir of the common gitdir (`git rev-parse --git-common-dir`): in a
    ///    linked worktree, hooks live in the MAIN repository's `.git/hooks`, not under the
    ///    worktree's private gitdir, so joining `.git/hooks` onto the worktree would install a hook
    ///    that is never read.
    fn hooks_dir(&self) -> Result<(PathBuf, bool)> {
        // Any non-local scope? (config precedence: local wins when both set)
        let foreign = self
            .run_with_output(&["config", "--get", "core.hooksPath"])
            .is_ok_and(|v| !v.trim().is_empty());
        if let Ok(local) = self.run_with_output(&["config", "--local", "--get", "core.hooksPath"]) {
            let local = local.trim();
            if !local.is_empty() {
                let path = PathBuf::from(local);
                let dir = if path.is_absolute() {
                    path
                } else {
                    self.path.join(path)
                };
                return Ok((dir, false));
            }
        }
        let common = self.run_with_output(&["rev-parse", "--git-common-dir"])?;
        let path = PathBuf::from(common.trim());
        let dir = if path.is_absolute() {
            path
        } else {
            self.path.join(path)
        };
        Ok((dir.join("hooks"), foreign))
    }

    /// Like [`Repo::open`], but walk up from `start` until a directory with a
    /// `.git` entry is found.
    ///
    /// Git runs the clean/smudge filter processes from the worktree root,
    /// but manual invocations from subdirectories should work too. This is
    /// a strict superset of `Repo::open` at the repo root, and every CLI
    /// command resolves its repo through here.
    pub fn discover(start: impl AsRef<Path>) -> Result<Self> {
        debug_assert!(start.as_ref().is_absolute(), "given path must be absolute");
        let mut dir = start.as_ref().to_path_buf();
        loop {
            let dot_git = dir.join(".git");
            if dot_git.is_dir() || dot_git.is_file() {
                return Self::open(&dir);
            }
            if !dir.pop() {
                return Err(Error::Other(format!(
                    "not a git repository: {}",
                    start.as_ref().display()
                )));
            }
        }
    }

    /// Whether the clean/smudge filter integration is installed in this repo.
    #[must_use]
    pub fn filter_installed(&self) -> bool {
        self.get_raw_config(&format!("filter.{}.required", gitattributes::FILTER_NAME))
            .is_ok()
    }

    /// Install the git filter integration: export `.gitattributes` and
    /// configure the clean/smudge filter driver plus the plaintext-diff
    /// textconv (transcrypt-style). After this, encryption and decryption
    /// are driven by git itself and the working tree stays plaintext.
    ///
    /// A git-se managed pre-commit hook is removed: it checks worktree
    /// files, which are plaintext on purpose in filter mode, so it would
    /// block every commit. Foreign hooks are kept (a warning is printed).
    pub fn install_filter(&self) -> Result<()> {
        // 0. Analyze the install-time migration before touching anything. Its `git checkout --force
        //    HEAD -- <paths>` resets the index as well as the worktree, so staged user changes on
        //    the affected paths must be surfaced as a hard error instead of being silently
        //    discarded.
        let has_key = self.get_key().is_ok();
        let plan = if has_key {
            Some(self.migration_plan()?)
        } else {
            None
        };
        if let Some(plan) = &plan
            && !plan.to_decrypt.is_empty()
            && self.has_staged_changes(&plan.to_decrypt)?
        {
            return Err(Error::Other(format!(
                "install would reset {} staged crypt-list file(s) via `git checkout --force HEAD \
                 --` (it rewrites the index too); commit them first or unstage them (`git restore \
                 --staged <path>`), then re-run install",
                plan.to_decrypt.len()
            )));
        }

        // Absolute exe path survives PATH changes; forward slashes work in
        // both POSIX sh and MSYS sh; single quotes make it shell-safe.
        let exe = std::env::current_exe()
            .map_err(|e| Error::Other(format!("failed to locate the running executable: {e}")))?;
        let quoted = quote_exe_for_sh(&exe);

        // 1. Export the managed .gitattributes block.
        let attr_path = self.path.join(".gitattributes");
        let content = match std::fs::read_to_string(&attr_path) {
            Ok(content) => content,
            // A missing .gitattributes is the common case: start from empty.
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
            // Any other read failure (encoding, permissions) must surface:
            // continuing with an empty base would clobber the user's file
            // with a block-only rewrite below.
            Err(e) => {
                return Err(Error::Other(format!(
                    "failed to read {}: {e}",
                    attr_path.display()
                )));
            },
        };
        let patterns = self.filter_patterns();
        let updated = gitattributes::with_managed_block(&content, &patterns);
        atomic_write(&attr_path, updated.as_bytes())?;

        // 2. Configure the filter driver and the diff textconv.
        let f = format!("filter.{}", gitattributes::FILTER_NAME);
        self.set_raw_config(&format!("{f}.clean"), &format!("{quoted} clean %f"))?;
        self.set_raw_config(&format!("{f}.smudge"), &format!("{quoted} smudge %f"))?;
        // Fail loudly (instead of committing plaintext) when the filter
        // cannot run, e.g. the binary was moved.
        self.set_raw_config(&format!("{f}.required"), "true")?;
        self.set_raw_config(
            &format!("diff.{}.textconv", gitattributes::FILTER_NAME),
            &format!("{quoted} diff"),
        )?;

        // 3. The legacy check hook is incompatible with filter mode. Look it up where install_hook
        //    would have put it (core.hooksPath-aware).
        let (hooks_dir, _) = self.hooks_dir()?;
        let hook = hooks_dir.join("pre-commit");
        if is_managed_hook(&hook)? {
            std::fs::remove_file(&hook)?;
            println!(
                "{} legacy pre-commit hook (incompatible with filter mode)",
                "Removed".yellow().bold()
            );
        } else if hook.exists() {
            warn!(
                "A foreign pre-commit hook exists at {}; it may block commits in filter mode.",
                hook.display()
            );
        }

        // 4. Decrypt the working tree where it is safe to do so.
        let (decrypted, needs_renormalize) = plan.as_ref().map_or((0, false), |plan| {
            (self.execute_migration(plan), plan.needs_renormalize)
        });

        println!(
            "{} git filter integration at {}",
            "Installed".green().bold(),
            self.path.display()
        );
        println!(
            "{}",
            "Working-tree files stay plaintext; git encrypts them on `git add` and decrypts on \
             checkout."
                .dimmed()
        );
        if !has_key {
            println!(
                "{}",
                "Run `git-se p` to set the password before staging files.".yellow()
            );
            return Ok(());
        }
        if decrypted > 0 {
            println!(
                "{} decrypted {decrypted} tracked file(s) in the working tree",
                "Auto".green().bold()
            );
        }
        if needs_renormalize {
            println!(
                "{}",
                "Some blobs need re-staging; run `git add --renormalize .` to encrypt them."
                    .yellow()
            );
        }
        Ok(())
    }

    /// Refresh the managed `.gitattributes` block after crypt-list changes.
    ///
    /// No-op unless the block already exists (i.e. filter mode is active);
    /// the hook-only workflow never touches `.gitattributes`.
    pub fn refresh_gitattributes(&self) -> Result<()> {
        let attr_path = self.path.join(".gitattributes");
        let Ok(content) = std::fs::read_to_string(&attr_path) else {
            return Ok(());
        };
        if !gitattributes::has_managed_block(&content) {
            return Ok(());
        }
        let updated = gitattributes::with_managed_block(&content, &self.filter_patterns());
        if updated != content {
            atomic_write(&attr_path, updated.as_bytes())?;
        }
        Ok(())
    }

    /// Final gitignore-style patterns for the crypt list: directory entries
    /// get a `/**` suffix (a bare directory pattern does not cascade to its
    /// contents in `.gitattributes`).
    fn filter_patterns(&self) -> Vec<String> {
        self.conf
            .crypt_list
            .iter()
            .map(|entry| {
                // The `/**` suffix is a real glob and must stay inside the
                // quotes when the path itself needs quoting, so it is passed
                // as a suffix rather than appended to the escaped pattern.
                if self.path.join(entry).is_dir() {
                    gitattributes::escape_pattern(entry, "/**")
                } else {
                    gitattributes::escape_pattern(entry, "")
                }
            })
            .collect()
    }

    /// Crypt-list files staged for the current commit, with the oid of their
    /// staged (index) blob: `Vec<(repo-relative path, oid)>`.
    ///
    /// Two git processes total, regardless of file count:
    /// - `git diff --cached --name-only -z --no-renames --diff-filter=ACMR` enumerates the staged
    ///   paths raw (NUL-separated; `-z` disables C-quoting so any byte spelling survives).
    ///   `--no-renames` keeps records single-path (a rename would drag the old path along).
    /// - `git ls-files -s -z` maps every index path to its full blob oid (`diff --raw` abbreviates
    ///   oids, which could turn ambiguous in huge repositories; ls-files never does).
    fn staged_crypt_blobs(&self) -> Result<Vec<(String, String)>> {
        let names = self.run_with_output_bytes(&[
            "diff",
            "--cached",
            "--name-only",
            "-z",
            "--no-renames",
            "--diff-filter=ACMR",
        ])?;
        if names.is_empty() {
            return Ok(Vec::new());
        }
        let index = self.index_blobs()?;
        Ok(nul_records(&names)
            .filter(|p| crypt_covers(&self.conf.crypt_list, &String::from_utf8_lossy(p)))
            .filter_map(|p| {
                index
                    .get(p)
                    .map(|oid| (String::from_utf8_lossy(p).into_owned(), oid.clone()))
            })
            .collect())
    }

    /// Full blob oid for every staged path, keyed by raw path bytes.
    /// (`git ls-files -s -z`: `<mode> <oid> <stage>\t<path>` per NUL.)
    fn index_blobs(&self) -> Result<HashMap<Vec<u8>, String>> {
        let out = self.run_with_output_bytes(&["ls-files", "-s", "-z"])?;
        let mut map = HashMap::new();
        for record in nul_records(&out) {
            let Some((meta, path)) = split_byte_record(record, b'\t') else {
                continue;
            };
            let Some(oid) = meta.split(|&b| b == b' ').nth(1) else {
                continue;
            };
            map.insert(path.to_vec(), String::from_utf8_lossy(oid).into_owned());
        }
        Ok(map)
    }

    /// Raw path bytes → full blob oid for every blob in the HEAD tree
    /// (`git ls-tree -r -z HEAD`: `<mode> <type> <oid>\t<path>` per NUL).
    /// Empty when HEAD does not exist yet (fresh repository).
    fn head_tree_blobs(&self) -> Result<BTreeMap<Vec<u8>, String>> {
        if !self.head_exists()? {
            return Ok(BTreeMap::new());
        }
        let out = self.run_with_output_bytes(&["ls-tree", "-r", "-z", "HEAD"])?;
        let mut map = BTreeMap::new();
        for record in nul_records(&out) {
            let Some((meta, path)) = split_byte_record(record, b'\t') else {
                continue;
            };
            let mut fields = meta.split(|&b| b == b' ');
            let kind = fields.nth(1);
            let oid = fields.next();
            // Keep blobs only; submodules (commit entries) are not files.
            if kind == Some(b"blob")
                && let Some(oid) = oid
            {
                map.insert(path.to_vec(), String::from_utf8_lossy(oid).into_owned());
            }
        }
        Ok(map)
    }

    fn head_exists(&self) -> Result<bool> {
        let out = Command::new("git")
            .current_dir(&self.path)
            .args(["rev-parse", "--verify", "--quiet", "HEAD"])
            .output()?;
        Ok(out.status.success())
    }

    /// Transcrypt-style migration analysis at install time, over tracked
    /// crypt-list files whose worktree copy still equals the committed blob
    /// byte-for-byte (typical right after a clone, before any filter was
    /// installed). See [`MigrationPlan`] for the outcomes; executing the
    /// plan happens in [`Repo::execute_migration`].
    ///
    /// Unlike the pre-refactor code (one `git cat-file` spawn per file), the
    /// HEAD blobs are streamed through a single [`CatFileBatch`] session.
    fn migration_plan(&self) -> Result<MigrationPlan> {
        let mut plan = MigrationPlan::default();
        if self.conf.crypt_list.is_empty() {
            return Ok(plan);
        }
        let head = self.head_tree_blobs()?;
        if head.is_empty() {
            return Ok(plan); // unborn branch: nothing committed to migrate
        }
        let index = self.index_blobs()?;
        let mut batch = CatFileBatch::spawn(&self.path)?;
        for (path, oid) in &head {
            // Only files that are both committed and still tracked; a staged
            // deletion must not resurface through the tree side.
            if !index.contains_key(path) {
                continue;
            }
            let rel = String::from_utf8_lossy(path).into_owned();
            if !crypt_covers(&self.conf.crypt_list, &rel) {
                continue;
            }
            let Some(blob) = batch.blob(oid)? else {
                continue;
            };
            let blob_encrypted = is_ciphertext(&blob);
            let Ok(worktree) = std::fs::read(self.path.join(&rel)) else {
                if !blob_encrypted {
                    plan.needs_renormalize = true;
                }
                continue;
            };
            if worktree == blob {
                // untouched since the last checkout: safe to re-smudge
                if blob_encrypted {
                    plan.to_decrypt.push(rel);
                } else {
                    // committed as plaintext before the filter existed
                    plan.needs_renormalize = true;
                }
            } else if blob_encrypted && !is_ciphertext(&worktree) {
                // decrypted outside git (e.g. `git-se d`): the cached stat
                // no longer matches; renormalize refreshes it losslessly
                plan.needs_renormalize = true;
            } else if !blob_encrypted {
                // committed as plaintext before the filter existed
                plan.needs_renormalize = true;
            }
        }
        Ok(plan)
    }

    /// Run the force-checkout migration selected by `plan`: delete the
    /// worktree copies and `git checkout --force HEAD` them back so the
    /// smudge filter decrypts them. Returns the number of files decrypted.
    fn execute_migration(&self, plan: &MigrationPlan) -> usize {
        // Chunk to stay clear of argv length limits on huge crypt lists.
        let mut decrypted = 0;
        'chunks: for chunk in plan.to_decrypt.chunks(64) {
            for rel in chunk {
                let _ = std::fs::remove_file(self.path.join(rel));
            }
            let mut args: Vec<&str> = vec!["checkout", "--force", "HEAD", "--"];
            args.extend(chunk.iter().map(String::as_str));
            match Command::new("git")
                .current_dir(&self.path)
                .args(&args)
                .output()
            {
                Ok(out) if out.status.success() => decrypted += chunk.len(),
                Ok(out) => {
                    warn!(
                        "git checkout failed during install: {}",
                        String::from_utf8_lossy(&out.stderr)
                    );
                    break 'chunks;
                },
                Err(e) => {
                    warn!("failed to run git checkout during install: {e}");
                    break 'chunks;
                },
            }
        }
        decrypted
    }

    /// Whether any of `paths` (repo-relative) differ between the index and
    /// HEAD, via `git diff --cached --quiet`: exit code 1 means differences
    /// exist, 0 means none.
    fn has_staged_changes(&self, paths: &[String]) -> Result<bool> {
        for chunk in paths.chunks(64) {
            let out = Command::new("git")
                .current_dir(&self.path)
                .args(["diff", "--cached", "--quiet", "--"])
                .args(chunk)
                .output()?;
            match out.status.code() {
                Some(0) => {},
                Some(1) => return Ok(true),
                _ => {
                    return Err(Error::Git(
                        String::from_utf8_lossy(&out.stderr).into_owned(),
                    ));
                },
            }
        }
        Ok(false)
    }

    /// Run a `git` command in the repo, discarding its stdout/stderr.
    pub fn run(&self, args: &[&str]) -> Result<()> {
        let output = Command::new("git")
            .current_dir(&self.path)
            .args(args)
            .output()?;
        if !output.status.success() {
            return Err(Error::Git(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }
        Ok(())
    }

    /// Run a `git` command and return its stdout as a `String`.
    pub fn run_with_output(&self, args: &[&str]) -> Result<String> {
        String::from_utf8(self.run_with_output_bytes(args)?)
            .map_err(|e| Error::Other(format!("git output not UTF-8: {e}")))
    }

    /// Run a `git` command and return its raw stdout bytes — the base for
    /// every `-z` (NUL-separated) parse, where text conversion would be
    /// lossy for arbitrary path bytes.
    fn run_with_output_bytes(&self, args: &[&str]) -> Result<Vec<u8>> {
        let mut cmd = Command::new("git");

        // Force English output in tests so we can match on stderr reliably.
        if cfg!(test) {
            cmd.env("LC_ALL", "C.UTF-8").env("LANGUAGE", "C.UTF-8");
        }

        let output = cmd.current_dir(&self.path).args(args).output()?;
        if !output.status.success() {
            return Err(Error::Git(
                String::from_utf8_lossy(&output.stderr).into_owned(),
            ));
        }
        Ok(output.stdout)
    }

    /// Write a value to `<prefix>.<key>` in the repo-local git config.
    ///
    /// The value never appears in a subprocess argv (process listings would
    /// briefly expose it — this key holds a user password): the local config
    /// file is edited directly with git-compatible escaping, falling back to
    /// a plain `git config` invocation only when the file cannot be parsed
    /// confidently (see [`Repo::set_local_config_file`]).
    ///
    /// Note: the value is stored verbatim (no trimming), so callers should
    /// sanitize it themselves if needed. This matters for the `key` field,
    /// which holds a user-supplied password and must not be silently modified.
    pub fn set_config(&self, key: &str, value: &str) -> Result<()> {
        let temp = String::from(GIT_CONFIG_PREFIX) + key;
        if let Err(e) = self.set_local_config_file(&temp, value) {
            debug!("direct config-file write failed ({e}); falling back to `git config` argv");
            return self.run(&["config", "--local", &temp, value]);
        }
        Ok(())
    }

    /// Set `section.var = value` by editing the repo-local config file
    /// directly, keeping the value out of every child process.
    ///
    /// `git config` has no stdin mode for writes (there is no `--stdin`
    /// option for it up to git 2.50), and an argv value is briefly visible
    /// in process listings. The value is escaped exactly the way git's own
    /// config writer does ([`escape_config_value`]), so the result is
    /// byte-compatible with git-written values and reads back identically
    /// (newlines, quotes, tabs, leading/trailing spaces, non-ASCII).
    fn set_local_config_file(&self, full_key: &str, value: &str) -> Result<()> {
        let Some((section, var)) = split_config_key(full_key) else {
            return Err(Error::Other(format!(
                "unsupported config key for file write: {full_key}"
            )));
        };
        let path = self.local_config_file()?;
        let content = match std::fs::read_to_string(&path) {
            Ok(content) => content,
            // A missing file is the fresh-repo case: start from empty.
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
            // Any other failure (encoding, permissions) must NOT be masked:
            // rewriting from an empty misread would clobber the user's config.
            Err(e) => return Err(e.into()),
        };
        let updated = set_config_line(&content, section, var, &escape_config_value(value));
        atomic_write(&path, updated.as_bytes())
    }

    /// Absolute path of the repo-local config file (the `git config --local`
    /// target). `--git-path config` resolves linked-worktree pointers to the
    /// shared config — the same file `--local` writes — and may return a
    /// repo-root-relative path.
    fn local_config_file(&self) -> Result<PathBuf> {
        let out = self.run_with_output(&["rev-parse", "--git-path", "config"])?;
        let path = PathBuf::from(out.trim());
        Ok(if path.is_absolute() {
            path
        } else {
            self.path.join(path)
        })
    }

    /// Write to an unprefixed git config key (e.g. `filter.git-se.clean`) in
    /// the repo-local config. Unlike [`Repo::set_config`], no namespace is
    /// prepended — used for the git integration settings git itself reads.
    /// These values are not secrets, so the plain argv form is fine.
    pub fn set_raw_config(&self, key: &str, value: &str) -> Result<()> {
        self.run(&["config", "--local", key, value])
    }

    /// Read an unprefixed key from the repo-local git config only (no
    /// global/system lookup, matching [`Repo::set_raw_config`]).
    ///
    /// The value is read with `-z` (NUL-terminated) so its exact bytes
    /// survive; trimming the LF of plain output would corrupt values that
    /// legitimately end in whitespace.
    pub fn get_raw_config(&self, key: &str) -> Result<String> {
        self.run_with_output_bytes(&["config", "--local", "--get", "-z", key])
            .map(|out| {
                // `--get` emits at most one record; cut at the first NUL
                // defensively anyway.
                let end = out.iter().position(|&b| b == 0).unwrap_or(out.len());
                String::from_utf8_lossy(&out[..end]).into_owned()
            })
    }

    /// Read `<prefix>.<key>` from the repo-local git config only.
    ///
    /// `--local` matches [`Repo::set_config`]: a stray key in the user's
    /// global/system config must not be silently adopted — it would surface
    /// as inexplicable decrypt failures in new repositories instead of a
    /// clear "key not set" error.
    pub fn get_config(&self, key: &str) -> Result<String> {
        let temp = String::from(GIT_CONFIG_PREFIX) + key;
        self.get_raw_config(&temp)
    }
}

/// Print the check summary; `Err(FilesNotEncrypted)` when anything is plain.
fn report_check(not_encrypted: &[String], total: usize) -> Result<()> {
    if not_encrypted.is_empty() {
        println!(
            "\n{}: All {} files are encrypted.",
            "Check complete".bold(),
            total.to_string().green(),
        );
        return Ok(());
    }

    println!(
        "\n{} files are {}:",
        not_encrypted.len().to_string().yellow(),
        "NOT encrypted".yellow()
    );
    for f in not_encrypted {
        println!("  - {f}");
    }

    println!(
        "\n{}: {}/{} files encrypted",
        "Check complete".bold(),
        (total - not_encrypted.len()).to_string().green(),
        total,
    );

    Err(Error::FilesNotEncrypted(not_encrypted.len(), total))
}

/// Install-time migration analysis of the tracked crypt files (the
/// transcrypt-style re-smudge performed by [`Repo::install_filter`]).
#[derive(Default)]
struct MigrationPlan {
    /// Tracked crypt files whose worktree copy still equals the committed
    /// (encrypted) blob byte-for-byte — safe to delete and force-checkout so
    /// the smudge filter decrypts them.
    to_decrypt: Vec<String>,
    /// Whether `git add --renormalize .` should be recommended afterwards:
    /// some blob was committed as plaintext before the filter existed, or
    /// some file was decrypted outside of git and its cached stat is stale.
    needs_renormalize: bool,
}

// ---------------------------------------------------------------------------
// Repo-local config file surgery (secret values never enter argv)
// ---------------------------------------------------------------------------

/// Split `section.var` for the plain (non-subsection) section syntax used
/// by all git-se keys.
///
/// Splits at the FIRST dot: a second dot would denote a
/// `[section "subsection"]` key, which this writer does not support.
fn split_config_key(key: &str) -> Option<(&str, &str)> {
    let (section, var) = key.split_once('.')?;
    (!section.is_empty() && !var.is_empty() && !var.contains('.')).then_some((section, var))
}

/// Escape a config value in git's double-quoted syntax, mirroring what
/// `git config` itself writes.
///
/// `\`, `"`, LF and TAB become their backslash escapes; every other byte
/// (CR and non-ASCII included) stays raw inside the quotes, exactly how git
/// serializes such values.
fn escape_config_value(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Whether a trimmed line is the plain section header `[section]`
/// (case-insensitive; a subsection form `[section "x"]` is a different key
/// namespace and never matches; a trailing comment is tolerated).
fn is_plain_section(trimmed: &str, section: &str) -> bool {
    trimmed
        .strip_prefix('[')
        .and_then(|rest| rest.split(']').next())
        .is_some_and(|name| name.trim().eq_ignore_ascii_case(section))
}

/// Whether a trimmed line assigns `var` (case-insensitive name, `=` with
/// optional spaces; comment lines never match because their pre-`=` text
/// contains the `#`/`;` marker).
fn is_var_assignment(trimmed: &str, var: &str) -> bool {
    trimmed
        .find('=')
        .is_some_and(|eq| trimmed[..eq].trim().eq_ignore_ascii_case(var))
}

/// Replace or insert `var = escaped_value` inside `[section]` of a config
/// file body, appending a fresh section when absent.
///
/// Line-oriented and conservative: existing lines outside the touched entry
/// are preserved verbatim.
fn set_config_line(content: &str, section: &str, var: &str, escaped_value: &str) -> String {
    let entry = format!("\t{var} = {escaped_value}");
    // split('\n') (not lines()) keeps any \r attached to line bodies, so a
    // CRLF file is not silently normalized; the trailing "" element
    // represents the final newline.
    let mut lines: Vec<String> = content.split('\n').map(str::to_string).collect();

    // Pass 1: an existing assignment of `var` inside the section?
    let mut in_section = false;
    let mut existing = None;
    for (i, line) in lines.iter().enumerate() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_section = is_plain_section(trimmed, section);
        } else if in_section && existing.is_none() && is_var_assignment(trimmed, var) {
            existing = Some(i);
        }
    }

    match existing {
        Some(i) => lines[i] = entry,
        None => {
            if let Some(header) = lines
                .iter()
                .position(|l| is_plain_section(l.trim(), section))
            {
                // Insert right below the section header.
                lines.insert(header + 1, entry);
            } else {
                lines.push(format!("[{section}]"));
                lines.push(entry);
            }
        },
    }
    let mut out = lines.join("\n");
    // Config files are newline-terminated; appending after a body without a
    // trailing newline (or to an empty one) must not break that.
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use std::process::Command;

    use path_absolutize::Absolutize;
    use tempfile::TempDir;

    use super::*;
    use crate::crypt::HEADER_LEN;

    #[test]
    fn test_repo_open() -> Result<()> {
        let repo = Repo::open(Path::new(".").absolutize()?)?;
        assert_eq!(repo.path().file_name().unwrap(), "git-simple-encrypt");
        let repo = Repo::open(Path::new("./.git").absolutize()?)?;
        assert_eq!(repo.path().file_name().unwrap(), "git-simple-encrypt");
        Ok(())
    }

    #[test]
    fn test_repo_open_rejects_non_git_directory() {
        let dir = TempDir::new().unwrap();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();

        let err = Repo::open(&repo_path).unwrap_err().to_string();
        assert!(err.contains("not a git repository"), "got: {err}");
    }

    #[test]
    fn test_repo_open_accepts_worktree_gitdir_pointer() -> Result<()> {
        // A linked worktree's `.git` is a file pointing at the main gitdir;
        // only its form (file vs directory) is checked here, validating the
        // target is git's own job.
        let dir = TempDir::new().unwrap();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        std::fs::write(
            repo_path.join(".git"),
            format!(
                "gitdir: {}\n",
                repo_path.join("main").join(".git").display()
            ),
        )?;

        let repo = Repo::open(&repo_path)?;
        assert_eq!(repo.path(), repo_path.as_path());
        Ok(())
    }

    fn init_temp_repo() -> TempDir {
        let dir = TempDir::new().unwrap();
        // `git init` so that .git/ exists for hook installation & config.
        Command::new("git")
            .args(["init"])
            .current_dir(dir.path())
            .output()
            .unwrap();
        dir
    }

    #[test]
    fn test_set_get_config_roundtrip() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        repo.set_config("key", "hunter2")?;
        let read_back = repo.get_config("key")?;
        assert_eq!(read_back, "hunter2");
        Ok(())
    }

    /// Passwords are config values too: every byte spelling that can come
    /// out of a terminal or argv must survive a write→read cycle untouched.
    ///
    /// This locks both the direct-file escaping and the `-z` exact read
    /// (a trimming read used to corrupt leading/trailing whitespace).
    #[test]
    fn test_set_get_config_special_value_roundtrip() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        let values = [
            "with space",
            "  padded  ",
            "a\"b\\c",
            "tab\there",
            "line1\nline2",
            "crlf\r\nend",
            "密码🔐パス",
            "#comment ;semi",
            "",
        ];
        for value in values {
            repo.set_config("key", value)?;
            assert_eq!(
                repo.get_config("key")?,
                value,
                "roundtrip failed for {value:?}"
            );
        }
        Ok(())
    }

    #[test]
    fn test_config_line_surgery() {
        // replace within existing section
        let base = "[core]\n\tbare = false\n[git-simple-encrypt]\n\tkey = \"old\"\n";
        assert_eq!(
            set_config_line(base, "git-simple-encrypt", "key", "\"new\""),
            "[core]\n\tbare = false\n[git-simple-encrypt]\n\tkey = \"new\"\n"
        );
        // insert into an existing section that lacks the var
        assert_eq!(
            set_config_line(base, "git-simple-encrypt", "other", "1"),
            "[core]\n\tbare = false\n[git-simple-encrypt]\n\tother = 1\n\tkey = \"old\"\n"
        );
        // append a missing section
        assert_eq!(
            set_config_line("[core]\n\tbare = false\n", "git-se", "k", "v"),
            "[core]\n\tbare = false\n\n[git-se]\n\tk = v\n"
        );
        // case-insensitive section/var matching, subsections never match
        let mixed = "[Git-Simple-Encrypt]\nKEY = x\n[git-simple-encrypt \"sub\"]\n\tkey = y\n";
        assert_eq!(
            set_config_line(mixed, "git-simple-encrypt", "key", "\"z\""),
            "[Git-Simple-Encrypt]\n\tkey = \"z\"\n[git-simple-encrypt \"sub\"]\n\tkey = y\n"
        );
        // empty body
        assert_eq!(set_config_line("", "s", "v", "1"), "\n[s]\n\tv = 1\n");
    }

    /// The managed-hook marker must stay the template's second line; the
    /// detection in `is_managed_hook` depends on it.
    #[test]
    fn test_pre_commit_hook_marker_line() {
        let hook = pre_commit_hook("'/some/exe'");
        assert!(hook.starts_with(b"#!/bin/sh\n"));
        let second = hook.split(|&b| b == b'\n').nth(1).unwrap();
        assert_eq!(second, PRE_COMMIT_HOOK_MARKER);
        let text = String::from_utf8_lossy(&hook);
        assert!(text.contains("'/some/exe' check --staged"), "{text}");
    }

    #[test]
    fn test_install_hook_creates_file() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;

        repo.install_hook()?;
        let hook = repo_path.join(".git").join("hooks").join("pre-commit");
        assert!(hook.exists());
        let expected = pre_commit_hook(&quote_exe_for_sh(&std::env::current_exe()?));
        assert_eq!(std::fs::read(&hook)?, expected);

        // Reinstalling our own managed hook succeeds (overwrite/upgrade path).
        repo.install_hook()?;
        assert_eq!(std::fs::read(&hook)?, expected);
        Ok(())
    }

    #[test]
    fn test_install_hook_replaces_managed_and_rejects_foreign() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let repo = Repo::open(&repo_path)?;
        let hook = repo_path.join(".git").join("hooks").join("pre-commit");
        std::fs::create_dir_all(hook.parent().unwrap())?;
        let expected = pre_commit_hook(&quote_exe_for_sh(&std::env::current_exe()?));

        // An outdated managed hook (marker line present, different body) is
        // replaced with the current template.
        let old_managed = b"#!/bin/sh\n# Auto-generated by git-se install\ngit-se-old check\n";
        std::fs::write(&hook, old_managed)?;
        repo.install_hook()?;
        assert_eq!(std::fs::read(&hook)?, expected);

        // A foreign hook without the marker is never touched.
        let foreign = b"#!/bin/sh\necho my own hook\n";
        std::fs::write(&hook, foreign)?;
        assert!(matches!(repo.install_hook(), Err(Error::HookExists(_))));
        assert_eq!(std::fs::read(&hook)?, foreign);
        Ok(())
    }

    #[test]
    fn test_check_reports_unencrypted() -> Result<()> {
        let dir = init_temp_repo();
        let repo_path = dir.path().absolutize().unwrap().to_path_buf();
        let mut repo = Repo::open(&repo_path)?;

        // Add a plaintext file to the crypt list.
        std::fs::write(repo_path.join("plain.txt"), b"hello")?;
        repo.conf.add_one_path_to_crypt_list("plain.txt")?;

        // check should return FilesNotEncrypted.
        let result = repo.check(&[], false);
        assert!(matches!(result, Err(Error::FilesNotEncrypted(1, 1))));

        // Encrypt the file (cheap path: just give it a valid 64-byte GITSE header so
        // is_file_encrypted returns true), then check passes.
        let mut fake_header = vec![0u8; HEADER_LEN];
        fake_header[..5].copy_from_slice(b"GITSE");
        fake_header[5] = 3; // version
        std::fs::write(repo_path.join("plain.txt"), fake_header).unwrap();
        let result = repo.check(&[], false);
        assert!(result.is_ok());
        Ok(())
    }
}
