name: CI

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall -y --no-symlinks cargo-nextest
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: cargo fmt
        run: cargo fmt --all --check
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: cargo test
        run: cargo nextest run --all-features --locked --no-tests pass && cargo test --all-features --locked --doc
